name: Generate Terraform docs

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  docs:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'release-please--') }}
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      # Authenticate using the App as per: https://dev.to/dtinth/authenticating-as-a-github-app-in-a-github-actions-workflow-27co
      - name: Obtain a GitHub App
        id: githubAppAuth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
          echo "::add-mask::$TOKEN"
          echo "token=$TOKEN" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.githubAppAuth.outputs.token }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0
        with:
          git-push: "true"
          output-file: "README.md"
          output-format: markdown document
          output-method: "inject"
          working-dir: .
