on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  checkov-job:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'release-please--') }}
    # Set the agent to run on
    runs-on: ubuntu-latest
    name: checkov-action

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      ################################
      # Run Checkov against code base #
      ################################
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@91d83a10ac0ded65efb6b419accf0099665d2a9f
        with:
          log_level: ERROR
          config_file: ./.github/checkov-config.yml
